name       : logrotate
version    : 3.14.0
release    : 4
source     :
    - https://github.com/logrotate/logrotate/archive/3.14.0.tar.gz : 593bd4ed9bad7761b6ad3f2689e6ac7d369db15ac141abbc9a8d296663b035fd
license    : GPL-2.0
component  : system.utils
summary    : Rotates, compresses, removes and emails system log files
description: |
    logrotate is designed to ease administration of systems that generate large numbers of log files. It allows automatic rotation, compression, removal, and emailing of log files.
builddeps  :
    - pkgconfig(popt)
setup      : |
    %reconfigure --with-acl \
        --with-state-file-path=/var/lib/logrotate/logrotate.status
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 examples/logrotate.service $installdir/%libdir%/systemd/system/logrotate.service
    install -D -m00644 examples/logrotate.timer $installdir/%libdir%/systemd/system/logrotate.timer
    install -D -m00644 examples/logrotate-default $installdir/etc/logrotate.conf
    install -D -m00644 $pkgfiles/logrotate.tmpfiles $installdir/%libdir%/tmpfiles.d/logrotate.conf
